# -*- coding: utf-8 -*-
"""Proyecto3-fcc_book_recommendation_knn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ospm3m8G5YS97kOa2lu--V4ZT6t0CdyS

*Note: You are currently reading this using Google Colaboratory which is a cloud-hosted version of Jupyter Notebook. This is a document containing both text cells for documentation and runnable code cells. If you are unfamiliar with Jupyter Notebook, watch this 3-minute introduction before starting this challenge: https://www.youtube.com/watch?v=inN8seMm7UI*

---

In this challenge, you will create a book recommendation algorithm using **K-Nearest Neighbors**.

You will use the [Book-Crossings dataset](http://www2.informatik.uni-freiburg.de/~cziegler/BX/). This dataset contains 1.1 million ratings (scale of 1-10) of 270,000 books by 90,000 users. 

After importing and cleaning the data, use `NearestNeighbors` from `sklearn.neighbors` to develop a model that shows books that are similar to a given book. The Nearest Neighbors algorithm measures distance to determine the “closeness” of instances.

Create a function named `get_recommends` that takes a book title (from the dataset) as an argument and returns a list of 5 similar books with their distances from the book argument.

This code:

`get_recommends("The Queen of the Damned (Vampire Chronicles (Paperback))")`

should return:

```
[
  'The Queen of the Damned (Vampire Chronicles (Paperback))',
  [
    ['Catch 22', 0.793983519077301], 
    ['The Witching Hour (Lives of the Mayfair Witches)', 0.7448656558990479], 
    ['Interview with the Vampire', 0.7345068454742432],
    ['The Tale of the Body Thief (Vampire Chronicles (Paperback))', 0.5376338362693787],
    ['The Vampire Lestat (Vampire Chronicles, Book II)', 0.5178412199020386]
  ]
]
```

Notice that the data returned from `get_recommends()` is a list. The first element in the list is the book title passed in to the function. The second element in the list is a list of five more lists. Each of the five lists contains a recommended book and the distance from the recommended book to the book passed in to the function.

If you graph the dataset (optional), you will notice that most books are not rated frequently. To ensure statistical significance, remove from the dataset users with less than 200 ratings and books with less than 100 ratings.

The first three cells import libraries you may need and the data to use. The final cell is for testing. Write all your code in between those cells.
"""

# import libraries (you may add additional imports but you may not have to)
import numpy as np
import pandas as pd
from scipy.sparse import csr_matrix
from sklearn.neighbors import NearestNeighbors
import matplotlib.pyplot as plt

# get data files
!wget https://cdn.freecodecamp.org/project-data/books/book-crossings.zip

!unzip book-crossings.zip

books_filename = 'BX-Books.csv'
ratings_filename = 'BX-Book-Ratings.csv'

# import csv data into dataframes
df_books = pd.read_csv(
    books_filename,
    encoding = "ISO-8859-1",
    sep=";",
    header=0,
    names=['isbn', 'title', 'author'],
    usecols=['isbn', 'title', 'author'],
    dtype={'isbn': 'str', 'title': 'str', 'author': 'str'})

df_ratings = pd.read_csv(
    ratings_filename,
    encoding = "ISO-8859-1",
    sep=";",
    header=0,
    names=['user', 'isbn', 'rating'],
    usecols=['user', 'isbn', 'rating'],
    dtype={'user': 'int32', 'isbn': 'str', 'rating': 'float32'})

# add your code here - consider creating a new cell for each section of code

"""1. Do NOT remove the 0 values.

2. Remove users that appear < 200 times in the list and books that have < 100 users from df_ratings (using the isbn column for the latter). This should be done at the same time (i.e. you can’t just remove users first then books from the resulting dataset).

3. Now merge df_ratings with df_books.

4. Drop the title duplicates with the default keep='first' parameter setting (so no need to get the max or the mean rating for the duplicated bunch) when using the drop_duplicates function.

5. For your final answer, the recommendations sublist should be in backwards order for some reason to pass.

**Clean data**
"""

# Mutate count columns
df_ratings['count_users'] = df_ratings.groupby(['user'], group_keys=False).transform('count')['rating']
df_ratings['count_books'] = df_ratings.groupby(['isbn'], group_keys=False).transform('count')['rating']

# Clean data
df_ratings = df_ratings.loc[(df_ratings.count_users >= 200) & (df_ratings.count_books >= 100)]
df_ratings = df_ratings[['user','isbn','rating']]

# Merge dataframes
df = pd.merge(df_ratings, df_books, on="isbn")

# Remove duplicates (Same user several reviews over same book)
df = df.drop_duplicates(subset=['user','title'])

# Transpose dataframe to have tittle vs users with values in each cell. Introduce 0's for NAs.
dfknn = df.pivot(index='title', columns='user', values='rating').fillna(0)

dfknn.shape

# Get list of titles (Books)
titles = list(dfknn.index.values)

# Functions to transform title to index and get row values for the title
def title_2_index(data, title, titles=titles):
  ind = titles.index(title)
  return ind, data.values[ind,:]

def index_2_title(ind, titles=titles):
  return titles[ind]

# Examples modify title to index
x, y = title_2_index(dfknn, '1984')
print('Index:', x)
print('First 10 values in the row:', y[1:10])
print('Book name from index:', index_2_title(x))

# Model (Euclidean distance - p=2)
neigh = NearestNeighbors(metric="cosine",algorithm="brute")
neigh.fit(dfknn.values)

"""**Recommendation**"""

# Function to return the closest five point (recommended books) - Closest because the radius is minimum. The first point is 0 beacuse is our target point.
def get_recommends(book = "", titles=titles, neighbors=5):
  ind, val = title_2_index(dfknn, book)
  pred = neigh.kneighbors(np.reshape(val,[1,-1]),len(titles),return_distance=True)
  # I give all the list but extract the last 5 (Highest probability)
  prob_val = pred[0][0][1:neighbors+1]
  prob_ind = pred[1][0][1:neighbors+1]
  pred = []
  for num in range(len(prob_val)):
    pred.append([index_2_title(prob_ind[num]), prob_val[num]])
  # Create output
  pred = pred[::-1]
  recommended_books = [book, pred]
  return recommended_books

get_recommends('1984')

"""Use the cell below to test your function. The `test_book_recommendation()` function will inform you if you passed the challenge or need to keep trying."""

books = get_recommends("Where the Heart Is (Oprah's Book Club (Paperback))")
print(books)

def test_book_recommendation():
  test_pass = True
  recommends = get_recommends("Where the Heart Is (Oprah's Book Club (Paperback))")
  if recommends[0] != "Where the Heart Is (Oprah's Book Club (Paperback))":
    test_pass = False
  recommended_books = ["I'll Be Seeing You", 'The Weight of Water', 'The Surgeon', 'I Know This Much Is True']
  recommended_books_dist = [0.8, 0.77, 0.77, 0.77]
  for i in range(2): 
    if recommends[1][i][0] not in recommended_books:
      test_pass = False
    if abs(recommends[1][i][1] - recommended_books_dist[i]) >= 0.05:
      test_pass = False
  if test_pass:
    print("You passed the challenge! 🎉🎉🎉🎉🎉")
  else:
    print("You havn't passed yet. Keep trying!")

test_book_recommendation()